import Head from 'next/head'
import About from '../components/About'
import Blog from '../components/Blog'
import Hero from '../components/Hero'
import Layout from '../components/Layout'
import Portfolio from '../components/Portfolio'
import styles from '../styles/Home.module.css'

export default function Home({ devDotToPosts }) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Cindy Arbelaez Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <About />
        <Portfolio />
        <Blog data={devDotToPosts}/>
      </Layout>
    </div>
  )
}

export const getStaticProps = async () => {
  const devDotToPosts = await fetch(
    `https://dev.to/api/articles?username=${process.env.DEV_USERNAME}`
  );
  
  const res = await devDotToPosts.json();
  return {
    props: {
      devDotToPosts: res
    },
    revalidate: 10,
  };
};